### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by jgiemza** [halasadi/plotmaps#2]
Hello,

I have few questions.

1. Just to be sure what is exactly plotted : are mrates the dispersal rates ? and Nsizes - the population density ?
2. My coordinates are in the different projection than the default one. It was possible to add the appropriate country contour in EEMS with option projection.in="". Is it / will it be available in MAPS ?
3. There was an option in EEMS to average plots over multiple runs ? Is it possible in MAPS ? Or maybe unnecassary, on the image in MAPS description it looks like an average / median profile is drawn ?
4. Excuse me for more MAPS rather than plotmaps related question. Is it possible to add more iterations after the estimation is finished ? Tried to do it specyfing prevpath, but I got Segmentation fault.

Thanks,
Joanna

**Comment by halasadi** [comment]
Sorry for getting to you so late! We posted a preprint of the paper today: https://www.biorxiv.org/content/early/2018/07/09/365536

1) You have the options to plot both. For empirical data, the migration rates and population sizes do not have a clear interpretation while dispersal rates and densities have a physical interpretation. In MAPS, if you specify add.countries = TRUE, then the migration rates and population sizes are automatically converted to dispersal and densities.

2) Currently, we use the mercator projection. 
    g = g + coord_map("mercator", parameters=NULL,  xlim=bbox[c('left', 'right')],
There is currently no options to use other projection, but maybe you can try changing that line to suit your needs? I will also add that as an option when I get a chance.

3) Yes, absolutely. In our paper, we average over runs. 

4) Ah yes, good catch. I will update the code. 

I'll update the code when I have a chance. I'll be offline this whole week and starting a new job so it might take a while.

**Comment by halasadi** [comment]
I fixed bug #4. For #3, you can try experimenting with changing the line I specified (line 482 to be exact); here is a list of possible projections I found: https://www.rdocumentation.org/packages/mapproj/versions/1.2.6/topics/mapproject
